# MySQL.  Versions 5.0+ are recommended.
# Ensure the MySQL gem is defined in your Gemfile
# gem 'mysql2', '~> 0.3.18'
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root                        # Ubuntu 14.04 and Mac Desktop
#  password: root                        # Ubuntu 14.04
#  socket: /var/run/mysqld/mysqld.sock   # Ubuntu 14.04
  password:                            # Mac Desktop
  socket: /tmp/mysql.sock              # Mac Desktop

# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment. See also the comment below production database.

development:
  <<: *default
  database: railsapp_development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: railsapp_test

production:
  <<: *default
  database: railsapp_production

#  You may have a full connection URL available as an environment variable.
#  For example: DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#  You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
